[package]
name = "vocabulary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
rand = "0.8.5"

[dev-dependencies]
pretty_assertions = "1.3.0"